title: Lee Ko
description: Introduction to Lee

#baseurl: "" # the subpath of your site, e.g. /blog

baseurl: https://leesdata.github.io

#theme: “just-the-docs”
#remote_theme: pmarsceill/just-the-docs

#repository: just-the-docs/just-the-docs # for github-metadata

#permalink: pretty



#logo: "/assets/images/just-the-docs.png"

aux_links:  Template Repository: https://github.com/just-the-docs/just-the-docs-template


#https://stackoverflow.com/questions/56464757/trouble-implementing-specifically-just-the-docs-theme-using-jekyll
