title: Lee Ko
description: Introducing Lee
remote_theme: pmarsceill/just-the-docs

url: https://leesdata.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
