title: Lee Ko : Data with Impact
description: Introducing Lee
theme: just-the-docs

url: https://leesdata.github.io/doc/Introduction.html

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
